name: Revalidate ISR WarmUp
on:
  schedule:
    - cron: '5 0 * * *'   # Every day at 00:05 UTC
    - cron: '5 12 * * *'  # Every day at 12:05 UTC
  workflow_dispatch:      # Manual trigger if needed

jobs:
  call-warmup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ISR warm-up endpoint
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            https://anime-tracker-next-js.vercel.app/api/cron/isr_warmUp/warmUp)
          
          echo "HTTP Response Code: $response"
          
          if [ "$response" -eq 200 ]; then
            echo "✅ ISR warm-up successful"
          else
            echo "❌ ISR warm-up failed with HTTP $response"
            exit 1
          fi